### PR TITLE
set up css and create components

### PR DESCRIPTION
**Pull request by jincheng411**

### CODE REVIEW

**Comment by laenalea** [comment]
Should we be ignoring the index.test.js for now @jincheng411 ? The test results is giving this error:  Details:

    /Users/anna/HackReactor/FEC/thirdTimesACharm/RelatedProducts/public/css/style.css:2
    img {
        ^

    SyntaxError: Unexpected token '{'

    > 1 | import './style.css';

Otherwise, look good to me!

**Review by laenalea — COMMENTED** [review]
Other than the minor jest test error, all looks good.

**Review by laenalea — APPROVED** [review]

**Comment by momo1113** [comment]
Did see the css file in any folder.

**Review by momo1113 — APPROVED** [review]
Structure looks good. I did't see the css file, other than that it looks good to me.

**Comment by jincheng411** [comment]
> Structure looks good. I did't see the css file, other than that it looks good to me.

css file is inside of public/css directory
@momo1113

**Comment by gusfel** [comment]
looks good to me

**Review by gusfel — APPROVED** [review]
looks good

**Pull request merged**
