### PR TITLE
Css v4

### PR DESCRIPTION
**Pull request by gusfel**
added styled buttons and changed how clicked images were displayed in the new review modal.  also added click tracking.

still need to add animation to new review modal

### CODE REVIEW

**Comment by laenalea** [comment]
> Get some error from bundle:
> 
> ERROR in ./src/index.jsx
> Module build failed (from ./node_modules/babel-loader/lib/index.js):
> Error: [BABEL] /Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/src/index.jsx: .ssr is not a valid Plugin property
> 
> * Maybe you meant to use
>   "plugin": [
>   ["babel-plugin-styled-components", {
>   "ssr": false
>   }]
>   ]
>   To be a valid plugin, its name and options should be wrapped in a pair of brackets
>   at /Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/@babel/core/lib/config/validation/plugins.js:65:42
>   at Array.forEach ()
>   at validatePluginObject (/Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/@babel/core/lib/config/validation/plugins.js:54:20)
>   at /Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/@babel/core/lib/config/full.js:269:55
>   at Generator.next ()
>   at Function. (/Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
>   at Generator.next ()
>   at step (/Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/gensync/index.js:261:32)
>   at evaluateAsync (/Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/gensync/index.js:291:5)
>   at Function.errback (/Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/gensync/index.js:113:7)
> 
> webpack 5.24.2 compiled with 1 error in 1341 ms

I got the same error

**Comment by gusfel** [comment]
@laenalea @momo1113 i took out the ssr thing

**Review by momo1113 — APPROVED** [review]
No reviews showed this time. but I can see lots of printout from console.

**Comment by gusfel** [comment]
> No reviews showed this time. but I can see lots of printout from console.

yeah, sometimes it does that.  i'm not sure why.

**Comment by gusfel** [comment]
> > Get some error from bundle:
> > ERROR in ./src/index.jsx
> > Module build failed (from ./node_modules/babel-loader/lib/index.js):
> > Error: [BABEL] /Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/src/index.jsx: .ssr is not a valid Plugin property
> > 
> > * Maybe you meant to use
> >   "plugin": [
> >   ["babel-plugin-styled-components", {
> >   "ssr": false
> >   }]
> >   ]
> >   To be a valid plugin, its name and options should be wrapped in a pair of brackets
> >   at /Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/@babel/core/lib/config/validation/plugins.js:65:42
> >   at Array.forEach ()
> >   at validatePluginObject (/Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/@babel/core/lib/config/validation/plugins.js:54:20)
> >   at /Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/@babel/core/lib/config/full.js:269:55
> >   at Generator.next ()
> >   at Function. (/Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
> >   at Generator.next ()
> >   at step (/Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/gensync/index.js:261:32)
> >   at evaluateAsync (/Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/gensync/index.js:291:5)
> >   at Function.errback (/Users/momosun/workspace/hackreactor/FEC/thirdTimesACharm/Reviews/node_modules/gensync/index.js:113:7)
> > 
> > webpack 5.24.2 compiled with 1 error in 1341 ms
> 
> I got the same error

these are resolved now!

**Review by jincheng411 — APPROVED** [review]

**Pull request merged**
