### PR TITLE
Newrcss

### PR DESCRIPTION
**Pull request by gusfel**
finished basic styling of new review modal.

please let me know of any styling ideas you may have

things i still need to do:
- add click tracking
- add animations to new review modal appearing and/or getting new reviews
- figure out how to handle clicks on photos added in the new review modal.  they pop up above where you're looking and the greyed background doesn't extend to the whole screen

### CODE REVIEW

**Review by laenalea — APPROVED** [review]
Looks great! The add review modal pops up by default upon loading the page though. Otherwise, I had fun playing around with the functionality

**Comment by gusfel** [comment]
> Looks great! The add review modal pops up by default upon loading the page though. Otherwise, I had fun playing around with the functionality

oops, i set it like that to test the modal.  just set it back to normal now

**Review by momo1113 — APPROVED** [review]
Looks so complete! Can not wait put everything together to see how it looks!!

**Review by jincheng411 — APPROVED** [review]
Looks great!

**Pull request merged**
